### ISSUE TITLE
Add a way to mark a milestone/event as done?

### ISSUE THREAD

**Issue by jsoares** [pathfindertools/scaling-filecoin#10]
@suzannaaltman how hard would it be to add the ability to mark a roadmap entry as done? The straightforward option would be just a checkmark, though alternatives would be fine too.

![image](https://user-images.githubusercontent.com/547492/206582314-ca6a409e-32f5-466e-b7f9-69943a7bc338.png)

**Comment by suzannaaltman** [comment]
@jsoares - shouldn't be bad to add that. I'll work on it Monday :)
