### ISSUE TITLE
Improve footer alignment

### ISSUE THREAD

**Issue by jsoares** [pathfindertools/scaling-filecoin#2]
![image](https://user-images.githubusercontent.com/547492/202728045-ca5fca91-8cc8-4c60-b83c-3126676f9e83.png)

Improve horizontal and vertical alignment between logo and link blocks; not sure how exactly, but something looks off now as the image is a component body item and the other columns have titles

**Comment by suzannaaltman** [comment]
@jsoares - I've adjusted this to give the image more space and also prevent the image from become HUGE on mid-sized screens. Let me know what you think.

**Comment by jsoares** [comment]
It still looks a little weird to me -- I'd expect the image to be top-aligned with the headings -- but I trust your aesthetics over mine.

**Comment by suzannaaltman** [comment]
@jsoares - the image is top aligned but the actual image file has extra padding at the top. Would you like me to crop and replace the image?

**Comment by suzannaaltman** [comment]
@jsoares - image updated. Take a look and let me know what you think.
