### ISSUE TITLE
Bottom padding / image-text alignments for features

### ISSUE THREAD

**Issue by jsoares** [pathfindertools/scaling-filecoin#6]
![image](https://user-images.githubusercontent.com/547492/204583470-605c3a1c-7d75-4751-a6fe-d1b2a4b8bf79.png)

I think this is me not figuring out the right set of levers but I can't seem to find a way to bottom pad the second feature to match the top padding on the first feature without messing up the intra-block alignment between text and image. Help @suzannaaltman ? 🙏

**Comment by suzannaaltman** [comment]
@jsoares - Padding adjusted. Take a look and let me know what you think
